version: '2'
services:
    nacos:
        image: nacos/nacos-server:latest
        container_name: nacos
        hostname: nacos
        environment:
            - MODE=standalone
        ports:
            - 8848:8848
        networks:
            my_net4:
                ipv4_address: 172.24.1.2
    mysql2:
        image: mysql:5.7
        container_name: mysql2
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        volumes:
            - "./db1:/var/lib/mysql"
            - "./conf1/my.cnf:/etc/my.cnf"
            - "./init1:/docker-entrypoint-initdb.d/"
        networks:
            my_net4:
                ipv4_address: 172.24.1.4
    demo:
        build: ./../demo/target
        ports:
            - 8080:8080
        container_name: demo
        restart: always
        depends_on:
            -  nacos
              # volumes: #/host-path:/container-path
              #- /Users/sunyifei/IdeaProjects/timon_02/target/ssw.sh:/usr/bin/ssw.sh
        entrypoint: "bash /usr/bin/wait-for-it.sh nacos:8848 -- java  -jar /app.jar"
        networks:
            my_net4:
                ipv4_address: 172.24.1.5
    consumer:
        build: ./../consumer/target
        ports:
            - 8082:8082
        depends_on:
             - nacos
             - demo
        entrypoint: "bash /usr/bin/wait-for-it.sh -t 30 service:8080 -- java  -jar /app.jar"
        restart: always
        networks:
            my_net4:
                ipv4_address: 172.24.1.6
    seata-server:
            image: myseata:v2
            hostname: myseata
            ports:
                - "8091:8091"
            networks:
                my_net4:
                    ipv4_address: 172.24.1.8

networks:
    my_net4:
        driver: bridge
        ipam:
            config:
                - subnet:  172.24.1.0/24
                  gateway: 172.24.1.1
